old

diff --git a/src/neko/neko.in b/src/neko/neko.in
--- a/src/neko/neko.in
+++ b/src/neko/neko.in
@@ -784,23 +784,49 @@ npk_emerge() {
 }
 
 npk_upgrade() {
-	local outdated pkg
+	unset FORCE NEEDED
+
+	FORCE="yes"
+	NEEDED="no"
 
 	msg "Checking for updates"
+	rm -rf /tmp/updates
+
 	for pkg in $(rpm -qa --queryformat='%{NAME}\n' $rootopt --dbpath /var/lib/rpm | sort -n | uniq); do
-		if [ -n "$(find_portdir $pkg)" ]; then
+		if [ ! -z "$(find_portdir $pkg)" ]; then
 			vercmp "$(find_instver $pkg)" "$(find_portver $(basename $pkg))"
 			if [ $? = 255 ]; then
-				if [ -n "$outdated" ]; then
-					outdated="$outdated $pkg"
-				else
-					outdated="$pkg"
-				fi
+				echo "$(basename $pkg)" >> /tmp/updates
 			fi
 		fi
 	done
 
-	echo -e "\n$outdated\n"
+	if [ ! -f "/tmp/updates" ]; then
+		warn "No updates were found"
+		rm -rf /tmp/updates
+		exit 0
+	fi
+
+	msg "Following packages will be updated"
+	for updated in $(cat /tmp/updates); do
+		printf "[\e[0;32mUP\e[0m] $updated "
+	done
+	echo; echo
+
+	(
+		for updated in $(cat /tmp/updates); do
+			if [ -z "$(cat $maskfile | grep -w $updated)" ]; then
+				npk_emerge $updated
+			fi
+		done
+	)
+	if [ $? != 0 ]; then
+		rm -rf /tmp/updates
+		die "Failed to update your system"
+	fi
+
+	rm -rf /tmp/updates
+	msg "System was updated successfuly!"
 }
 
 npk_search() {
